"""
Text-based SDR report extraction.
"""
import re
import pdfplumber
from pathlib import Path
from datetime import datetime
from typing import List, Optional

from models.schema import (
    SDRReport, OperatorDetails, UPIVPAAccount, SocialMediaAccount,
    CompromisedService, PersonalDetails, SecurityScores, DetectionSummary, TelecomInfo
)

from extractor.normalizer import normalize_sdr_data


def extract_text_pdf(pdf_path: str) -> SDRReport:
    """
    Extract SDR report data from a text-based PDF.
    """
    report = SDRReport(source_file=pdf_path, extraction_method="text")

    try:
        with pdfplumber.open(pdf_path) as pdf:
            full_text = ""
            for page in pdf.pages:
                full_text += page.extract_text() + "\n"

            report_type = _detect_report_type_from_content(full_text)
            report.report_type = report_type

            if report_type == "khoj_osint":
                report = _extract_khoj_osint_report(report, full_text)
            elif report_type == "scaninfoga":
                report = _extract_scaninfoga_report(report, full_text)
            else:
                report.warnings.append(f"Unknown report type detected")

    except Exception as e:
        report.warnings.append(f"Extraction failed: {str(e)}")

    # Normalize before returning
    try:
        report = normalize_sdr_data(report)
    except Exception:
        pass

    return report


def _detect_report_type_from_content(text: str) -> str:
    """Detect report type from content patterns."""
    text_lower = text.lower()

    if "osint report" in text_lower and "operator details" in text_lower:
        return "khoj_osint"
    elif "scaninfoga" in text_lower or "comprehensive intelligence report" in text_lower:
        return "scaninfoga"
    elif "security score" in text_lower and "cibil score" in text_lower:
        return "scaninfoga"
    elif "alias" in text_lower and "email address" in text_lower:
        return "khoj_osint"

    return "unknown"


def _extract_khoj_osint_report(report: SDRReport, text: str) -> SDRReport:
    """Extract data from Khoj OSINT reports."""

    # Extract phone number from title
    phone_match = re.search(r'OSINT Report - (\d+)', text)
    if phone_match:
        report.phone_number = phone_match.group(1)

    # Extract report metadata
    report_generated_match = re.search(r'Report Generated by:\s*(\d+)', text)
    if report_generated_match:
        report.report_generated_by = report_generated_match.group(1)

    datetime_match = re.search(r'Report Generation Date/Time:\s*([^\n]+)', text)
    if datetime_match:
        try:
            # Parse datetime (format: 2026-03-23 11:09 IST)
            dt_str = datetime_match.group(1).strip()
            # Remove IST and parse
            dt_str = dt_str.replace('IST', '').strip()
            report.report_generation_datetime = datetime.strptime(dt_str, '%Y-%m-%d %H:%M')
        except:
            pass

    # Extract operator details
    operator_match = re.search(r'Operator:\s*([^\n]+)', text)
    if operator_match:
        report.operator_details.operator = operator_match.group(1).strip()

    circle_match = re.search(r'Circle:\s*([^\n]+)', text)
    if circle_match:
        report.operator_details.circle = circle_match.group(1).strip()

    # Extract aliases (from "Alias" section)
    alias_section = _extract_section(text, "Alias", ["Email Address", "UPI/VPA Accounts"])
    if alias_section:
        aliases = [line.strip() for line in alias_section.split('\n') if line.strip() and len(line.strip()) > 2]
        report.aliases = aliases

    # Extract email addresses
    email_section = _extract_section(text, "Email Address", ["UPI/VPA Accounts", "Locations"])
    if email_section:
        emails = re.findall(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', email_section)
        report.email_addresses = list(set(emails))  # Remove duplicates

    # Extract UPI/VPA accounts
    upi_section = _extract_section(text, "UPI/VPA Accounts", ["Locations", "Accounts -"])
    if upi_section:
        upi_accounts = []
        upi_lines = [l.strip() for l in upi_section.split('\n') if l.strip()]
        
        i = 0
        while i < len(upi_lines):
            line = upi_lines[i]
            if 'UPI:' in line:
                upi_id = re.search(r'UPI:\s*([^\s]+)', line)
                # Check next line for App/Bank
                bank_name = "Unknown"
                if i + 1 < len(upi_lines) and 'App/Bank:' in upi_lines[i+1]:
                    bank_match = re.search(r'App/Bank:\s*([^\n]+)', upi_lines[i+1])
                    if bank_match:
                        bank_name = bank_match.group(1).strip()
                    i += 1 # Skip next line as we consumed it
                
                if upi_id:
                    upi_accounts.append(UPIVPAAccount(
                        upi_id=upi_id.group(1).strip(),
                        app_bank=bank_name
                    ))
            i += 1
        report.upi_vpa_accounts = upi_accounts

    # Extract locations
    locations_section = _extract_section(text, "Locations \\(Approx\\)", ["Accounts -", "Social Media"])
    if locations_section:
        locations = [loc.strip() for loc in locations_section.split('\n') if loc.strip()]
        report.locations = locations

    # Extract social media accounts and compromised data
    social_media_section = _extract_section(text, "Social Media Account Identifiers", ["Possible Account Existence"])
    if social_media_section:
        social_accounts = []
        compromised_services = []

        lines = social_media_section.split('\n')
        current_service = None
        current_data = []

        for line in lines:
            line = line.strip()
            if not line:
                continue

            # Check for service name followed by compromised data
            service_match = re.match(r'^([^-]+)\s*-\s*(.+)$', line)
            if service_match:
                # Save previous service if exists
                if current_service and current_data:
                    compromised_services.append(CompromisedService(
                        service_name=current_service,
                        compromised_data=current_data
                    ))

                current_service = service_match.group(1).strip()
                data_str = service_match.group(2).strip()
                current_data = [d.strip() for d in data_str.split(',') if d.strip()]

            elif current_service and "Compromised Data:" in line:
                # Extract compromised data
                data_match = re.search(r'Compromised Data:\s*(.+)', line)
                if data_match:
                    data_items = [d.strip() for d in data_match.group(1).split(',') if d.strip()]
                    current_data.extend(data_items)

        # Save last service
        if current_service and current_data:
            compromised_services.append(CompromisedService(
                service_name=current_service,
                compromised_data=current_data
            ))

        report.compromised_services = compromised_services

    return report


def _extract_scaninfoga_report(report: SDRReport, text: str) -> SDRReport:
    """Extract data from Scaninfoga reports."""

    # Extract phone number
    phone_match = re.search(r'Investigating Number:\s*\+?(\d+)', text)
    if phone_match:
        report.phone_number = phone_match.group(1)

    # Extract personal details
    name_match = re.search(r'Name:\s*([^\n]+)', text)
    if name_match:
        report.personal_details.full_name = name_match.group(1).strip()

    email_match = re.search(r'Email:\s*([^\n]+)', text)
    if email_match:
        report.personal_details.other_email = email_match.group(1).strip()

    # Extract security scores
    security_score_match = re.search(r'Security Score\s+(\d+)', text)
    if security_score_match:
        report.security_scores.security_score = int(security_score_match.group(1))

    cibil_score_match = re.search(r'CIBIL Score\s+(\d+)', text)
    if cibil_score_match:
        report.security_scores.cibil_score = int(cibil_score_match.group(1))

    # Extract detection summary
    total_accounts_match = re.search(r'Total Accounts\s+(\d+)', text)
    if total_accounts_match:
        report.detection_summary.total_accounts = int(total_accounts_match.group(1))

    upi_platforms_match = re.search(r'UPI Platforms\s+(\d+)', text)
    if upi_platforms_match:
        report.detection_summary.upi_platforms = int(upi_platforms_match.group(1))

    verified_checks_match = re.search(r'Verified Checks\s+(\d+)', text)
    if verified_checks_match:
        report.detection_summary.verified_checks = int(verified_checks_match.group(1))

    suspected_match = re.search(r'Suspected Detections\s+(\d+)', text)
    if suspected_match:
        report.detection_summary.suspected_detections = int(suspected_match.group(1))

    # Extract telecom info
    number_active_match = re.search(r'Number\s+(\w+)\s+Country', text)
    if number_active_match:
        active_str = number_active_match.group(1).lower()
        report.telecom_info.number_active = active_str == "yes"

    country_match = re.search(r'Country\s+(\w+)', text)
    if country_match:
        report.telecom_info.country = country_match.group(1)

    country_prefix_match = re.search(r'Country Prefix\s*([^\n]+)', text)
    if country_prefix_match:
        report.telecom_info.country_prefix = country_prefix_match.group(1).strip()

    return report


def _extract_section(text: str, start_pattern: str, end_patterns: List[str]) -> Optional[str]:
    """Extract a section of text between start and end patterns."""
    start_match = re.search(start_pattern, text, re.IGNORECASE)
    if not start_match:
        return None

    start_pos = start_match.end()
    end_pos = len(text)

    # Find the earliest end pattern
    for end_pattern in end_patterns:
        end_match = re.search(end_pattern, text[start_pos:], re.IGNORECASE)
        if end_match:
            end_pos = min(end_pos, start_pos + end_match.start())

    return text[start_pos:end_pos].strip()